### PR TITLE
Added clarification on Width units

### LINKED ISSUE #58: Add clear definition of dashboard panel width (1-10)
It is currently `128 + 144(n-1)` pixels. Don't know if it's the best way to describe it but can note it somehow.

### PR DESCRIPTION
**Pull request by TreZc0**
This should be sufficient to allow users to get an idea of the width units.
A note could be added that these settings can easily be adjusted in the package.json afterwards.
resolves #58

### CODE REVIEW

**Comment by Hoishin** [comment]
Can't tell if it's better to write `16 + 144n`.... 🙄

**Comment by TreZc0** [comment]
`144n - 16` right? Should be the same result and probably the least confusing math equation.

**Comment by Hoishin** [comment]
@TreZc0 I think it's been enough to merge this :P If you have time, would you mind pulling master branch and maybe update the equation?

**Comment by Hoishin** [comment]
Thank you!

**Pull request merged**
